/**
 * Format the PR comment markdown for GitHub.
 */
export function formatPRComment(
  run,
  sandboxResult,
  securityResult,
  coverageResult,
  runId
) {
  const statusIcon = sandboxResult.failed === 0 ? '✅' : '❌'
  const riskIcon =
    {
      critical: '🔴',
      high: '🟠',
      medium: '🟡',
      low: '🔵',
      clean: '🟢',
    }[securityResult.overallRisk] || '⚪'
  const severityIcon = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵',
    info: '⚪',
  }

  const findings = securityResult.findings || []
  const findingsTable =
    findings.length > 0
      ? `### Security findings (${findings.length})\n| Severity | File | Issue |\n|----------|------|-------|\n` +
        findings
          .sort(
            (a, b) =>
              ['critical', 'high', 'medium', 'low', 'info'].indexOf(
                a.severity
              ) -
              ['critical', 'high', 'medium', 'low', 'info'].indexOf(
                b.severity
              )
          )
          .slice(0, 10)
          .map(
            (f) =>
              `| ${severityIcon[f.severity] || '⚪'} ${f.severity} | \`${f.file}:${f.line}\` | ${(f.description || '').slice(0, 80)} |`
          )
          .join('\n')
      : '### Security\n✅ No findings'

  const gaps = coverageResult.gaps || []
  const highGaps = gaps.filter((g) => g.priority === 'high')
  const coverageSection =
    highGaps.length > 0
      ? `### Coverage gaps (${highGaps.length} high priority)\n` +
        highGaps
          .slice(0, 5)
          .map(
            (g) =>
              `- \`${g.functionOrBlock}\` in \`${g.file}\` — ${g.suggestedTestDescription}`
          )
          .join('\n')
      : '### Coverage\n✅ No critical gaps identified'

  return `## 🤖 PRbøt Results

**Status**: ${statusIcon} ${sandboxResult.passed} passed / ${sandboxResult.failed} failed
**Coverage score**: ${coverageResult.coverageScore ?? 'N/A'}%
**Security risk**: ${riskIcon} ${securityResult.overallRisk}

${findingsTable}

${coverageSection}

---
*Generated by PRbøt in ${run.duration ? Math.round(run.duration / 1000) + 's' : 'N/A'} · [View full report](http://localhost:5173/runs/${runId})*`
}
